/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package presentacion;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author gta_2
 */
public class IFrmTemporizador extends javax.swing.JInternalFrame {
    private Timer mTimer;
    private int segundos = 30;
    private int milisegundos = 0;
    /**
     * Creates new form IFrmTemporizador
     */
    public IFrmTemporizador() {
        initComponents();
        mTimer = new Timer(10, (ActionEvent e) -> {
         IniciarTemporizador();   
        });
    }
    private void IniciarTemporizador(){
        ActualizaTiempo();
        ActualizaLabel();
        VerificarFin();
    }
    private void ActualizaTiempo(){
        milisegundos--;
        
        if(milisegundos <0){
            milisegundos = 66;
            segundos--;
        }
        
    }
    private void ActualizaLabel(){
        String temporizador = segundos + "s . " + milisegundos + "ms ";
        lblTemp.setText(temporizador);
    }
    private void VerificarFin() {
        if (segundos <= 0 && milisegundos <= 0) {
            mTimer.stop(); 
            JOptionPane.showMessageDialog(this, "¡El tiempo se ha agotado!", "Hagan Juego", JOptionPane.INFORMATION_MESSAGE);
            btnIniciar.setEnabled(true); 
        }
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTemp = new javax.swing.JPanel();
        lblTemp = new javax.swing.JLabel();
        btnIniciar = new javax.swing.JButton();

        panelTemp.setBackground(new java.awt.Color(0, 102, 102));

        lblTemp.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTemp.setText("30s : 0ms");

        btnIniciar.setText("Iniciar Apuesta");
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelTempLayout = new javax.swing.GroupLayout(panelTemp);
        panelTemp.setLayout(panelTempLayout);
        panelTempLayout.setHorizontalGroup(
            panelTempLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTempLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(panelTempLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnIniciar)
                    .addComponent(lblTemp))
                .addContainerGap(209, Short.MAX_VALUE))
        );
        panelTempLayout.setVerticalGroup(
            panelTempLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTempLayout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addComponent(lblTemp)
                .addGap(18, 18, 18)
                .addComponent(btnIniciar)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTemp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTemp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        segundos = 30;
        milisegundos = 0;
        ActualizaLabel();
        mTimer.start();
        btnIniciar.setEnabled(false);
        
    }//GEN-LAST:event_btnIniciarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciar;
    private javax.swing.JLabel lblTemp;
    private javax.swing.JPanel panelTemp;
    // End of variables declaration//GEN-END:variables
}
